# Generated by Django 3.2.8 on 2021-10-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_auto_20211024_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='iframe',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='profile_img_and_files'),
        ),
    ]
