# Generated by Django 3.2.8 on 2021-10-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_auto_20211026_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='iframe',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
